name: qemu-virgil
base: core18
adopt-info: qemu
summary: QEMU as a snap, built from latest git with some fancy graphics extras
description: |
  The latest QEMU as a snap package with GTK, SDL2 and Virgil 3D enabled

  To read more about QEMU see https://www.qemu.org/
  To read more about Virgil 3D support go to https://virgil3d.github.io/

  The snap package source can be found at https://github.com/ogra1/qemu-virgil-snap

  If your system supports kvm please make sure to connect the kvm interface after
  you installed qemu-virgl.

  sudo snap connect qemu-virgil:kvm

  Then you can run the VM like below.

  qemu-virgil -enable-kvm -m 512 -device virtio-vga,virgl=on -display sdl,gl=on \
    -netdev user,id=ethernet.0,hostfwd=tcp::10022-:22 -device rtl8139,netdev=ethernet.0 \
    -soundhw ac97 some.img

  For qemu-system-arm and qemu-system-aarch64 VMs the snap ships the
  qemu-virgil.arm and qemu-virgil.arm64 commands.

grade: stable
confinement: strict

apps:
  qemu-virgil:
    command: usr/bin/qemu-system-x86_64
    environment:
        LIBGL_DRIVERS_PATH: $SNAP/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl/xorg
        LD_LIBRARY_PATH: $SNAP/usr/lib/qemu:$SNAP/usr/lib/x86_64-linux-gnu/mesa:$SNAP/usr/lib/x86_64-linux-gnu/mesa-egl:$SNAP/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl/xorg:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio:$LD_LIBRARY_PATH
        QEMU_AUDIO_DRV: pa
        FONTCONFIG_PATH: $SNAP/etc/fonts/conf.d
        FONTCONFIG_FILE: $SNAP_DATA/fonts.conf
        GDK_PIXBUF_MODULE_FILE: $SNAP_DATA/.gdk-pixbuf-loaders.cache
        XDG_DATA_DIRS: $SNAP/usr/share
    plugs:
      - x11
      - kvm
      - pulseaudio
      - desktop
      - home
      - opengl
      - raw-usb
      - screen-inhibit-control
      - network
      - network-bind
      - network-control
      - unity7
      - wayland
  arm64:
    command: usr/bin/qemu-system-aarch64
    environment:
        LIBGL_DRIVERS_PATH: $SNAP/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl/xorg
        LD_LIBRARY_PATH: $SNAP/usr/lib/qemu:$SNAP/usr/lib/x86_64-linux-gnu/mesa:$SNAP/usr/lib/x86_64-linux-gnu/mesa-egl:$SNAP/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl/xorg:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio:$LD_LIBRARY_PATH
        QEMU_AUDIO_DRV: pa
        FONTCONFIG_PATH: $SNAP/etc/fonts/conf.d
        FONTCONFIG_FILE: $SNAP_DATA/fonts.conf
        GDK_PIXBUF_MODULE_FILE: $SNAP_DATA/.gdk-pixbuf-loaders.cache
        XDG_DATA_DIRS: $SNAP/usr/share
    plugs:
      - x11
      - kvm
      - pulseaudio
      - desktop
      - home
      - opengl
      - raw-usb
      - screen-inhibit-control
      - network
      - network-bind
      - network-control
      - unity7
      - wayland
  arm:
    command: usr/bin/qemu-system-arm
    environment:
        LIBGL_DRIVERS_PATH: $SNAP/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl/xorg
        LD_LIBRARY_PATH: $SNAP/usr/lib/qemu:$SNAP/usr/lib/x86_64-linux-gnu/mesa:$SNAP/usr/lib/x86_64-linux-gnu/mesa-egl:$SNAP/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl/xorg:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio:$LD_LIBRARY_PATH
        QEMU_AUDIO_DRV: pa
        FONTCONFIG_PATH: $SNAP/etc/fonts/conf.d
        FONTCONFIG_FILE: $SNAP_DATA/fonts.conf
        GDK_PIXBUF_MODULE_FILE: $SNAP_DATA/.gdk-pixbuf-loaders.cache
        XDG_DATA_DIRS: $SNAP/usr/share
    plugs:
      - x11
      - kvm
      - pulseaudio
      - desktop
      - home
      - opengl
      - raw-usb
      - screen-inhibit-control
      - network
      - network-bind
      - network-control
      - unity7
      - wayland
  qemu-img:
    command: usr/bin/qemu-img
    plugs:
      - home

parts:
  virgl:
    source: git://anongit.freedesktop.org/virglrenderer
    plugin: autotools
    build-packages:
      - libgbm-dev
      - libdrm-dev
      - libegl1-mesa-dev
      - libepoxy-dev
      - libgtk-3-dev
      - libsdl2-dev
      - libgles2-mesa-dev
    stage-packages:
      - libepoxy0
  qemu:
    after: [ virgl ]
    source: git://git.qemu.org/qemu.git
    plugin: nil
    override-build: |
      set -e
      ./configure --target-list=x86_64-softmmu,aarch64-softmmu,arm-softmmu \
        --audio-drv-list=pa --prefix=/usr
      make
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install
      # fix execstack warning of review tools
      rm -fv $SNAPCRAFT_PART_INSTALL/usr/share/qemu/s390-ccw.img
      rm -fv $SNAPCRAFT_PART_INSTALL/usr/share/qemu/s390-netboot.img
      # set version
      snapcraftctl set-version "$(cat VERSION)"
    build-packages:
      - bison
      - flex
      - gettext
      - libaio-dev
      - libbluetooth-dev
      - libbrlapi-dev
      - libbz2-dev
      - libcap-dev
      - libcap-ng-dev
      - libcurl4-gnutls-dev
      - libgtk-3-dev
      - libibverbs-dev
      - libjpeg8-dev
      - libncurses5-dev
      - libnuma-dev
      - librbd-dev
      - librdmacm-dev
      - libsasl2-dev
      - libsdl1.2-dev
      - libseccomp-dev
      - libsnappy-dev
      - libssh2-1-dev
      - libusb-1.0-0-dev
      - libvde-dev
      - libvdeplug-dev
      - libvte-2.91-dev
      - libxen-dev
      - liblzo2-dev
      - libx11-dev
      - libepoxy-dev
      - libglib2.0-dev
      - libfdt-dev
      - libpixman-1-dev
      - zlib1g-dev
      - libnfs-dev
      - libiscsi-dev
      - libpulse-dev
    stage-packages:
      - hicolor-icon-theme
      - libegl1-mesa
      - libgl1-mesa-glx
      - libaio1
      - libasn1-8-heimdal
      - libasound2
      - libasyncns0
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libbluetooth3
      - libboost-iostreams1.62.0
      - libboost-random1.62.0
      - libboost-thread1.62.0
      - libbrlapi0.6
      - libcairo2
      - libcairo-gobject2
      - libcurl3-gnutls
      - libdatrie1
      - libflac8
      - libfontconfig1
      - libgdk-pixbuf2.0-0
      - libgraphite2-3
      - libgssapi3-heimdal
      - libgtk-3-0
      - libharfbuzz0b
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libiscsi7
      - libjpeg-turbo8
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnfs11
      - libnspr4
      - libnss3
      - libnuma1
      - libogg0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpulse0
      - librados2
      - librbd1
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libsdl2-2.0-0
      - libssh2-1
      - libsnappy1v5
      - libsndfile1
      - libsndio6.1
      - libthai0
      - libvdeplug2
      - libvorbis0a
      - libvorbisenc2
      - libvte-2.91-0
      - libwayland-cursor0
      - libwayland-egl1-mesa
      - libwind0-heimdal
      - libxcb-render0
      - libxcb-shm0
      - libxcomposite1
      - libxcursor1
      - libxen-4.9
      - libxenstore3.0
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxss1
      - ttf-ubuntu-font-family
